version: '2'

services:

  nginx:
    image: devdrops/nginx:v1.3
    volumes:
      - ./app:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - main
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
    volumes:
      - data:/var/lib/mysql
    networks:
      - main
    ports:
      - "3307:3306"

  php:
    image: devdrops/php-fpm:7.0
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - main
    depends_on:
      - mysql

networks:

  main:
    driver: 'bridge'

volumes:

  data:
    driver: 'local'
