################################
# DOCKER PHP ENVIRONMENT
#
# CREATED BY Davi Marcondes Moreira <davi.marcondes.moreira@gmail.com>
################################

version: '2'

services:

  nginx:
    image: devdrops/nginx:v1.4
    volumes:
      - ./app:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=newdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

  php:
    image: devdrops/php-fpm:7.0
    volumes:
      - ./app:/usr/share/nginx/html
    links:
      - mysql

volumes:

  dbdata:
    driver: 'local'
